### ISSUE TITLE
ADCDevice error Joystick

### ISSUE THREAD

**Issue by Techttv** [Freenove/Freenove_RFID_Starter_Kit_for_Raspberry_Pi#7]
When I try the Joystick program, raspberry send this output
`pi@pi:~/Freenove_ultimate/Code/Python_Code/12.1.1_Joystick $ python3 Joystick.py
Traceback (most recent call last):
  File "Joystick.py", line 13, in <module>
    adc = ADCDevice() # Define an ADCDevice class object
  File "/home/pi/Freenove_ultimate/Code/Python_Code/12.1.1_Joystick/ADCDevice.py                                                                       ", line 15, in __init__
    self.bus=smbus.SMBus(1)
FileNotFoundError: [Errno 2] No such file or directory
`
![pi@pi_ ~_Freenove_ultimate_Code_Python_Code_12 1 1_Joystick 30_03_2021 15_16_30](https://user-images.githubusercontent.com/62478271/112995280-59db3b00-916b-11eb-8878-fb401fa443c2.png)

**Comment by DenzelChen** [comment]
Dear customer,

Did you install smbus and adc library?
sudo apt get install python smbus
sudo apt get install python 3 smbus
![image](https://user-images.githubusercontent.com/22834809/113124607-4520a500-9248-11eb-8414-dd3dd8781894.png)

Please send an email to support@freenove.com if you have further concerns. Thank you.

Sincerely,
Freenove Support Team
